[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aegis-framework"
version = "1.0.0"
description = "High-performance multi-asset algorithmic trading execution framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.0",
    "numpy>=1.26.0"
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--cov=aegis --cov-report term-missing --cov-report html"
testpaths = ["tests"]
filterwarnings = [
    "error::pytest.PytestUnhandledThreadExceptionWarning"
]
#log_cli_format = "%(asctime)s [%(levelname)s][%(threadName)s][%(name)s:%(lineno)s] %(message)s"
log_cli_format = "%(asctime)s [%(levelname)8s][%(threadName)12s][%(module)30s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.coverage.run]
source = [
    "aegis",
]
omit = [
    "tests/*",
    "**/test_*.py"
]
branch = true

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:"
]

[[tool.mypy.overrides]]
module = "backtrader.*"
ignore_missing_imports = true

[tool.ruff]
src = ["aegis"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
lines-after-imports = 1
case-sensitive = false
known-first-party = ["aegis", "tests"]
from-first = true
split-on-trailing-comma = true
