"""Aegis Framework - Immutable Domain Model Specifications.

Defines unified structured storage data containers protecting type safety.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum

# =============================================================================
# -----------------------------------------------------------------------------
# =============================================================================

@dataclass(frozen=True)
class InstrumentSpecification:
    """Enforces compile-time type validation for multi-asset market parameters."""
    base_spread_ticks: float
    tick_size: float
    volatility_factor: float
    lot_size: int

# -----------------------------------------------------------------------------

class TransactionSide(Enum):
    """Enforces execution direction flags across internal accounting nodes."""
    LONG = "LONG"
    SHORT = "SHORT"

# -----------------------------------------------------------------------------

class OrderType(Enum):
    """Enforces structural routing parameter limitations for orders executions."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"

# -----------------------------------------------------------------------------

class OrderStatus(Enum):
    """Enforces compile-time type safety for asynchronous lifecycle states."""
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"

# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class OrderEvent:
    """Captures absolute transactional metadata generated during order updates."""
    order_id: int
    symbol: str
    status: OrderStatus
    side: TransactionSide
    executed_price: float
    executed_size: int
    timestamp: datetime

# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class OrderRequest:
    """Immutable data container representing a strategy trade intention.

    Attributes:
        symbol: The targeted financial asset identifier.
        stop_loss_ticks: The structural protection distance measured in ticks.
        risk_percentage: The maximum fraction of account equity risked on the trade.
        confidence_factor: A fractional scaling coefficient that can only reduce size.
    """
    symbol: str
    stop_loss_ticks: float
    risk_percentage: float
    confidence_factor: float

# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class PositionCloseEvent:
    """Encapsulates definitive accounting metrics records when a trade is finalized."""
    symbol: str
    side: TransactionSide
    pnl_gross: float
    pnl_net: float
    commission: float
    bars_duration: int
    entry_timestamp: datetime
    exit_timestamp: datetime

# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class MarketPricePoint:
    """Protects pricing snapshots matrix calculations from mutations."""
    timestamp: datetime
    mid_price: float
    bid: float
    ask: float
    current_atr: float
    is_night_tariff: bool = False

# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class RegimeConfidenceVector:
    """Stores statistical confidence metrics computed by math classifiers."""
    mean_reversion: float
    trending: float
    noise: float

# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class RiskValidationResult:
    """Immutable verdict profile generated by the risk management systems.

    Attributes:
        is_approved: Flag signaling if the intention complies with risk filters.
        calculated_volume_lots: The final calculated order size in standardized lots.
        rejection_reason: The descriptive reason detailing why an order was rejected.
    """
    is_approved: bool
    calculated_volume_lots: float
    rejection_reason: str

# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class TradeTelemetrySnapshot:
    """Captures explicable post-mortem operational metrics records snapshots."""
    timestamp: datetime
    indicator_value: float
    regime_vector: RegimeConfidenceVector

# =============================================================================
# -----------------------------------------------------------------------------
# =============================================================================
