from core.models import OrderRequest
from core.models import RiskValidationResult
from core.registry import InstrumentRegistry

# =============================================================================
# -----------------------------------------------------------------------------
# =============================================================================

class PositionSizer:
    """Universal sizing calculator bound by contract parameters and risk scores."""

# -----------------------------------------------------------------------------

    def __init__(self, instrument_registry: InstrumentRegistry) -> None:
        """Initialize the positioning engine with the global specifications mapping.

        Args:
            instrument_registry: Central database containing contract constants.
        """
        self._instrument_registry = instrument_registry

# -----------------------------------------------------------------------------

    def compute_volume(
        self,
        account_equity: float,
        order_request: OrderRequest,
    ) -> RiskValidationResult:
        """Calculate the optimized trading size using the calibrated risk equation.

        Formula:
            Lots = (Equity * Risk% * Confidence) / (StopLossTicks * TickLoss)

        Args:
            account_equity: The current total net asset value of the portfolio.
            order_request: The raw parameters of the trading request.

        Returns:
            The structured verdict containing the final calculated size.
        """
        if order_request.risk_percentage < 0.0 or order_request.confidence_factor < 0.0:
            return RiskValidationResult(
                is_approved=False,
                calculated_volume_lots=0.0,
                rejection_reason="Risk parameters cannot be negative.",
            )

        if order_request.confidence_factor > 1.0:
            return RiskValidationResult(
                is_approved=False,
                calculated_volume_lots=0.0,
                rejection_reason=(
                    "Confidence factor cannot amplify "
                    "maximum risk parameters."
                ),
            )

        spec = self._instrument_registry.get_specification(symbol=order_request.symbol)

        # Compute the monetary risk budget allowed for this trade session.
        risk_fraction = order_request.risk_percentage / 100.0
        risk_budget = account_equity * risk_fraction * order_request.confidence_factor

        # Compute the exact loss profile generated by one full contract lot.
        tick_loss_per_lot = spec.tick_size * spec.lot_size
        total_loss_per_lot = order_request.stop_loss_ticks * tick_loss_per_lot

        if total_loss_per_lot <= 0.0:
            return RiskValidationResult(
                is_approved=False,
                calculated_volume_lots=0.0,
                rejection_reason="Invalid risk or stop loss distance specification.",
            )

        # Derive raw volume and apply strict floor truncation matching broker step.
        raw_volume = risk_budget / total_loss_per_lot
        precision_multiplier = 1.0 / spec.lot_step
        truncated_volume = (
            (raw_volume * precision_multiplier // 1) / precision_multiplier
        )

        # Round to handle float representation inaccuracies.
        decimal_places = (
            len(str(spec.lot_step).split(".")) if "." in str(spec.lot_step) else 0
        )
        final_volume = round(truncated_volume, decimal_places)

        # Enforce contract safety boundaries via fail-fast verification.
        if final_volume < spec.min_lot:
            return RiskValidationResult(
                is_approved=False,
                calculated_volume_lots=0.0,
                rejection_reason="Calculated volume is below minimum contract size.",
            )

        return RiskValidationResult(
            is_approved=True,
            calculated_volume_lots=final_volume,
            rejection_reason="",
        )

# =============================================================================
# -----------------------------------------------------------------------------
# =============================================================================
